/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Bastien Genbrugge (https://sketchfab.com/bastienBGR)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/ship-in-clouds-c475323dc7f24e26ba2009c08c8e1941
title: Ship in Clouds
*/

import * as THREE from 'three';
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { GLTF } from 'three-stdlib';

type GLTFResult = GLTF & {
  nodes: {
    Sky_Mat_0: THREE.Mesh;
    Boot_Finaal_1_Boot_Finaal_0: THREE.Mesh;
    Cloud_Poly_Poly_0: THREE.Mesh;
    Cloud_1_Cloud_1_0: THREE.Mesh;
    Cloud_2_Cloud_2_0: THREE.Mesh;
    Cloud_3_Cloud_3_0: THREE.Mesh;
  };
  materials: {
    material: THREE.MeshStandardMaterial;
    Boot_Finaal: THREE.MeshStandardMaterial;
    Poly: THREE.MeshStandardMaterial;
    Cloud_1: THREE.MeshStandardMaterial;
    Cloud_2: THREE.MeshStandardMaterial;
    Cloud_3: THREE.MeshStandardMaterial;
  };
};

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>();
  const { nodes, materials } = useGLTF('/scene.gltf') as GLTFResult;
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[51.64, 0, -129.1]} rotation={[0, -Math.PI / 2, 0]}>
            <mesh
              geometry={nodes.Sky_Mat_0.geometry}
              material={materials.material}
            />
          </group>
          <group position={[7.53, -7.8, 0]} rotation={[0, -0.6, 0]}>
            <mesh
              geometry={nodes.Boot_Finaal_1_Boot_Finaal_0.geometry}
              material={materials.Boot_Finaal}
            />
          </group>
          {/* <mesh
            geometry={nodes.Cloud_Poly_Poly_0.geometry}
            material={materials.Poly}
          /> */}
          <group
            position={[-102.34, -152.02, -521.51]}
            rotation={[1.92, 0.43, 0.91]}
            scale={[1.5, 1.5, 1.5]}
          >
            <mesh
              geometry={nodes.Cloud_1_Cloud_1_0.geometry}
              material={materials.Cloud_1}
            />
          </group>
          <group
            position={[333.05, -63.93, -853.25]}
            rotation={[-2.9, 0.21, -1.17]}
            scale={[1.5, 1.5, 1.5]}
          >
            <mesh
              geometry={nodes.Cloud_2_Cloud_2_0.geometry}
              material={materials.Cloud_2}
            />
          </group>
          <group
            position={[339.37, -70.97, -883.27]}
            rotation={[2.89, -1.31, 3.08]}
            scale={[1.19, 1.19, 1.19]}
          >
            <mesh
              geometry={nodes.Cloud_3_Cloud_3_0.geometry}
              material={materials.Cloud_3}
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/scene.gltf');
